#!/bin/bash
# install.sh — push this repo's canonical files OUT to their deployed locations,
# then regenerate the derived skills/ bundle. Run after editing CONDUCTOR.md or
# anything under hooks/.
#
# WHY THIS EXISTS. The same two-step — copy CONDUCTOR.md outward, regenerate the
# bundle — was run by hand three times in one session, and the build went RED
# after each edit because one half was forgotten. That is gate 06's trigger met:
# repeated, mechanical, stable, and checkable by `lint/all.sh`.
set -euo pipefail
cd "$(dirname "$0")/.."

cp CONDUCTOR.md ~/.claude/skills/discipline/SKILL.md
for h in hooks/*.py; do cp "$h" ~/.claude/hooks/; done
for a in gates/*/[a-z]*-reader.md gates/*/[a-z]*-auditor.md; do
  [ -e "$a" ] && cp "$a" ~/.claude/agents/
done
bash ~/.claude/scripts/skill_share.sh >/dev/null 2>&1

rm -rf skills && mkdir skills
cp -R ~/.claude/skills-shareable/. skills/
rm -f skills/CONTRACT.md
# The plugin layout wants agents at the ROOT (2026-09-02). Same four files as
# skills/agents/, regenerated here so the two cannot drift by hand.
rm -rf agents && mkdir agents && cp skills/agents/*.md agents/
cat > skills/README.md <<'HDR'
# skills/ — GENERATED. Do not hand-edit.

> **GENERATED by `skill_share.sh`** from the private skill masters. Edits here are
> overwritten on the next run. Edit the master and regenerate.

The deployed forms of the discipline stack. The canonical, reviewed definition of
a gate lives in `gates/NN-<name>/GATE.md`. `agents/` holds the reviewer agents the
skills reference so cross-references resolve inside this bundle.
HDR
echo "installed outward + regenerated. Now: bash lint/all.sh"
