#!/bin/bash
# install.sh — push this repo's canonical files OUT to their deployed locations,
# then regenerate the derived skills/ bundle. Run after editing CONDUCTOR.md or
# anything under hooks/.
#
# WHY THIS EXISTS. The same two-step — copy CONDUCTOR.md outward, regenerate the
# bundle — was run by hand three times in one session, and the build went RED
# after each edit because one half was forgotten. That is gate 06's trigger met:
# repeated, mechanical, stable, and checkable by `lint/all.sh`.
set -euo pipefail
cd "$(dirname "$0")/.."

mkdir -p ~/.claude/skills/discipline ~/.claude/hooks ~/.claude/agents ~/.claude/scripts
cp CONDUCTOR.md ~/.claude/skills/discipline/SKILL.md
# the marker gate 13 reads: the deployed copies on this machine came from THIS clone
printf '%s\n' "$(pwd -P)" > ~/.claude/skills/discipline/.installed-from
for h in hooks/*.py; do cp "$h" ~/.claude/hooks/; done
# code forms the hooks and the shell both read (gate 02 budget, gate 19 calibration)
mkdir -p ~/.claude/scripts
# The two SessionStart/hygiene scripts. They were deployed-only until
# 2026-09-21: present on the laptop, absent from this repo, so `install.sh`
# could not restore them and a reimage would have silently removed the
# conductor's on-by-default block and the memory loader guard.
cp scripts/session_gate.sh ~/.claude/scripts/
cp scripts/memory_lint.sh  ~/.claude/scripts/
# link_scan.py is memory_lint.sh's link accounting, split out because inline
# python with backticks breaks the shell however the heredoc is quoted. It was
# created deployed-only on 2026-09-21 -- the exact failure the comment above
# describes, repeated the same day, which is why the drift check now covers
# every file this script deploys rather than the conductor and the hooks alone.
cp scripts/link_scan.py    ~/.claude/scripts/
# spec_lint: the mechanical half of the spec-driven skill (2026-09-22). Repo-sourced so
# nomess can see it; baited in lint/bait_spec_lint.py.
cp scripts/spec_lint.py     ~/.claude/scripts/
chmod +x ~/.claude/scripts/session_gate.sh ~/.claude/scripts/memory_lint.sh ~/.claude/scripts/link_scan.py ~/.claude/scripts/spec_lint.py
cp gates/02-retrieval-economy/budget.py ~/.claude/scripts/
cp gates/19-state-the-posterior/posterior.py ~/.claude/scripts/
cp gates/18-adversarial-pass/adversary.py ~/.claude/scripts/
# The deployed skill tree mirrors gates/ file-for-file and had NO WRITER: 18 .py
# files sat under ~/.claude/skills/discipline/gates/ that install.sh never
# copied. 17 happened to match; posterior.py had fallen behind and still carried
# the ratchet bug after the repo was fixed. An unmaintained copy still looks current -- give it a writer or delete it, never leave it.
rsync -a --delete --exclude '__pycache__' gates/ ~/.claude/skills/discipline/gates/
chmod +x ~/.claude/scripts/budget.py ~/.claude/scripts/posterior.py ~/.claude/scripts/adversary.py
# skills/ is CANONICAL (his order 2026-10-01: "every version of discipline, including
# the one you use, will be the same as what's on github"). Until then skills/ was
# GENERATED by skill_share.sh from private masters, so the copy the agent ran was not
# the copy on GitHub. Now the repo copy is the only copy: it is installed as-is on
# every machine, and machine-specific facts live in memory or ~/.config/discipline,
# never in a skill. The conductor is CONDUCTOR.md; skills/discipline/SKILL.md is
# written from it here so the plugin layout carries the same text.
cp CONDUCTOR.md skills/discipline/SKILL.md
for d in skills/*/; do
  n=$(basename "$d")
  [ "$n" = agents ] && continue
  [ -f "$d/SKILL.md" ] || continue
  mkdir -p ~/.claude/skills/"$n"
  cp "$d/SKILL.md" ~/.claude/skills/"$n"/SKILL.md
done
cp skills/agents/*.md ~/.claude/agents/
# The plugin layout wants agents at the ROOT (2026-09-02): a copy of skills/agents/.
rm -rf agents && mkdir agents && cp skills/agents/*.md agents/
echo "installed outward. Now: bash lint/all.sh"
