#!/bin/bash
# install.sh — push this repo's canonical files OUT to their deployed locations,
# then regenerate the derived skills/ bundle. Run after editing CONDUCTOR.md or
# anything under hooks/.
#
# WHY THIS EXISTS. The same two-step — copy CONDUCTOR.md outward, regenerate the
# bundle — was run by hand three times in one session, and the build went RED
# after each edit because one half was forgotten. That is gate 06's trigger met:
# repeated, mechanical, stable, and checkable by `lint/all.sh`.
set -euo pipefail
cd "$(dirname "$0")/.."

mkdir -p ~/.claude/skills/discipline ~/.claude/hooks ~/.claude/agents ~/.claude/scripts
cp CONDUCTOR.md ~/.claude/skills/discipline/SKILL.md
# the marker gate 13 reads: the deployed copies on this machine came from THIS clone
printf '%s\n' "$(pwd -P)" > ~/.claude/skills/discipline/.installed-from
for h in hooks/*.py; do cp "$h" ~/.claude/hooks/; done
# code forms the hooks and the shell both read (gate 02 budget, gate 19 calibration)
mkdir -p ~/.claude/scripts
# The two SessionStart/hygiene scripts. They were deployed-only until
# 2026-09-21: present on the laptop, absent from this repo, so `install.sh`
# could not restore them and a reimage would have silently removed the
# conductor's on-by-default block and the memory loader guard.
cp scripts/session_gate.sh ~/.claude/scripts/
cp scripts/memory_lint.sh  ~/.claude/scripts/
# link_scan.py is memory_lint.sh's link accounting, split out because inline
# python with backticks breaks the shell however the heredoc is quoted. It was
# created deployed-only on 2026-09-21 -- the exact failure the comment above
# describes, repeated the same day, which is why the drift check now covers
# every file this script deploys rather than the conductor and the hooks alone.
cp scripts/link_scan.py    ~/.claude/scripts/
# skill_share.sh is CALLED below (line ~45) but was never COPIED, and was
# tracked in no repo at all -- so on a fresh machine this script invoked a
# file that did not exist. It is the scrubber: it strips machine-specific
# blocks, private memory slugs, wikilinks and private paths out of the skill
# masters to make the shareable variants. Losing it loses the thing that
# keeps published skills free of his private references.
cp scripts/skill_share.sh  ~/.claude/scripts/
# spec_lint: the mechanical half of the spec-driven skill (2026-09-22). Repo-sourced so
# nomess can see it; baited in lint/bait_spec_lint.py.
cp scripts/spec_lint.py     ~/.claude/scripts/
# spec-driven: the skill itself, repo-sourced since 2026-09-27 (it had no source; the deployed copy was the only copy).
mkdir -p ~/.claude/skills/spec-driven && cp skills/spec-driven/SKILL.md ~/.claude/skills/spec-driven/SKILL.md
chmod +x ~/.claude/scripts/session_gate.sh ~/.claude/scripts/memory_lint.sh ~/.claude/scripts/link_scan.py ~/.claude/scripts/skill_share.sh ~/.claude/scripts/spec_lint.py
cp gates/02-retrieval-economy/budget.py ~/.claude/scripts/
cp gates/19-state-the-posterior/posterior.py ~/.claude/scripts/
cp gates/18-adversarial-pass/adversary.py ~/.claude/scripts/
# The deployed skill tree mirrors gates/ file-for-file and had NO WRITER: 18 .py
# files sat under ~/.claude/skills/discipline/gates/ that install.sh never
# copied. 17 happened to match; posterior.py had fallen behind and still carried
# the ratchet bug after the repo was fixed. An unmaintained copy still looks current -- give it a writer or delete it, never leave it.
rsync -a --delete --exclude '__pycache__' gates/ ~/.claude/skills/discipline/gates/
chmod +x ~/.claude/scripts/budget.py ~/.claude/scripts/posterior.py ~/.claude/scripts/adversary.py
for a in gates/*/[a-z]*-reader.md gates/*/[a-z]*-auditor.md gates/*/[a-z]*-adversary.md; do
  [ -e "$a" ] && cp "$a" ~/.claude/agents/
done
# Regenerating skills/ needs the PRIVATE scrub rules (the maintainer's machine only).
# Without them, say so and skip: never regenerate unscrubbed, and never die silently.
PRIVATE_SCRUB="${DISCIPLINE_PRIVATE_SCRUB:-$HOME/.config/discipline/scrub.sed}"
if [ ! -f "$PRIVATE_SCRUB" ]; then
  echo "install: skills/ NOT regenerated: no private scrub rules at $PRIVATE_SCRUB (a maintainer-only step; the deployed copies above are installed)" >&2
else
  bash ~/.claude/scripts/skill_share.sh >/dev/null
  # skills/spec-driven is repo-SOURCED (2026-09-27), not generated: keep it across the wipe.
  keep="$(mktemp -d)"; cp -R skills/spec-driven "$keep"/
  rm -rf skills && mkdir skills
  cp -R ~/.claude/skills-shareable/. skills/
  cp -R "$keep"/spec-driven skills/ && rm -rf "$keep"
  rm -f skills/CONTRACT.md
  # The plugin layout wants agents at the ROOT (2026-09-02). Same four files as
  # skills/agents/, regenerated here so the two cannot drift by hand.
  rm -rf agents && mkdir agents && cp skills/agents/*.md agents/
  cat > skills/README.md <<'HDR'
# skills/ — GENERATED. Do not hand-edit.

> **GENERATED by `skill_share.sh`** from the private skill masters. Edits here are
> overwritten on the next run. Edit the master and regenerate.

The deployed forms of the discipline stack. The canonical, reviewed definition of
a gate lives in `gates/NN-<name>/GATE.md`. `agents/` holds the reviewer agents the
skills reference so cross-references resolve inside this bundle.
HDR
fi
echo "installed outward. Now: bash lint/all.sh"
